### ISSUE TITLE
Unversioned shared library

### ISSUE THREAD

**Issue by aleasto** [ccxvii/mujs#186] opened 2024-01-26 10:17 UTC
A shared library should have a version that represents ABI stability across potentially multiple releases. An unversioned shared library is unusable for distribution.

At a glance the ABI seems to be quite stable, judging by the fact that MPV requires `dependency('mujs', version: '>= 1.0.0'`.
Please consider versioning the library, you may just start now at version 1. **The version shall change every time a new release breaks the ABI.**

See: https://docs.fedoraproject.org/en-US/packaging-guidelines/#_downstream_so_name_versioning

**Comment by ccxvii** [comment] 2024-01-26 13:38
Duplicate of #175

**Closed by ccxvii** 2024-01-26 13:38 UTC
